# Generated by Django 3.1.4 on 2020-12-24 02:01

from django.db import migrations, models
import fusion.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=fusion.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Designer'), ('lni-users', 'Usuário'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico')], max_length=12, verbose_name='Icone'),
        ),
    ]
